- name: Install docker-compose
  apt:
    name: docker-compose
    state: present

- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release

- name: Extract source-2-image tar from remote
  unarchive:
    src: https://github.com/openshift/source-to-image/releases/download/v1.3.1/source-to-image-v1.3.1-a5a77147-linux-amd64.tar.gz
    dest: /usr/local/bin
    remote_src: yes
    mode: 0777

- name: Clone playground repo
  ansible.builtin.git:
    repo: 'https://github.com/wip-abramson/aries-jupyter-playground'
    dest: /home/{{ username }}/aries-jupyter-playground
    version: 'demo/hl-global-forum'
    update: no


- name: Own directory
  file:
    path: "/home/{{ username }}/aries-jupyter-playground"
    state: directory
    owner: "{{ username }}"
    group: wheel
    mode: 0755
    recurse: yes
  become: yes

- name: Prepare env vars
  ansible.builtin.copy:
    src: /home/{{ username }}/aries-jupyter-playground/playground/{{ item.name }}/{{ item.path }}
    dest: /home/{{ username }}/aries-jupyter-playground/playground/{{ item.name }}/.env
    owner: "{{ username }}"
    group: wheel
    remote_src: yes
  with_items:
    - '{{ env_paths }}'

- name: Allow notebook port 8888:8889
  community.general.ufw:
    rule: allow
    port: 8888:8889
    proto: tcp

- name: Allow Agent HTTP port 3020
  community.general.ufw:
    rule: allow
    port: 3020
    proto: tcp

- name: Allow Agent HTTP port 4020
  community.general.ufw:
    rule: allow
    port: 4020
    proto: tcp